service: chess-api

plugins:    
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  runtime: nodejs16.x

functions:
  - ${file(./src/functions/test/serverless.yml)}

custom:
  typescript:
    functions:
      - getTest

resources:
  Resources:
    TestTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: TestTable-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        